apiVersion: v1
kind: Service
metadata:
  name: mdacosta-hello-spring-lb
spec:
  type: LoadBalancer
  selector:
    app: mdacosta-hello-spring
  ports:
      - protocol: TCP
        port: 80
        targetPort: 8080
        name: http