apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdacosta-hello-spring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mdacosta-hello-spring
  template:
    metadata:
      labels:
        app: mdacosta-hello-spring
    spec:
      containers:
          - image: lene626/hello-spring:k8s
            name: mdacosta-hello-spring
            imagePullPolicy: Always
            ports:
              - containerPort: 8080